// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQV4LZZh39qYt8rfEQ_GdycVDnxwCvtbo',
    appId: '1:692238134417:web:56c2148a0fd4061d3d2330',
    messagingSenderId: '692238134417',
    projectId: 'karaneeyaani',
    authDomain: 'karaneeyaani.firebaseapp.com',
    storageBucket: 'karaneeyaani.firebasestorage.app',
    measurementId: 'G-V0D7W83SWF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcqvZHPX7uM_WCbsgkb6WPYtSD8udJMtY',
    appId: '1:692238134417:android:f529055e7dd4f8503d2330',
    messagingSenderId: '692238134417',
    projectId: 'karaneeyaani',
    storageBucket: 'karaneeyaani.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXBEFYYlZWGZHjHNapKyiBjbnJXSoEoJg',
    appId: '1:692238134417:ios:03c382911d5c4a7a3d2330',
    messagingSenderId: '692238134417',
    projectId: 'karaneeyaani',
    storageBucket: 'karaneeyaani.firebasestorage.app',
    iosBundleId: 'com.example.karaneeyaani',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXBEFYYlZWGZHjHNapKyiBjbnJXSoEoJg',
    appId: '1:692238134417:ios:03c382911d5c4a7a3d2330',
    messagingSenderId: '692238134417',
    projectId: 'karaneeyaani',
    storageBucket: 'karaneeyaani.firebasestorage.app',
    iosBundleId: 'com.example.karaneeyaani',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQV4LZZh39qYt8rfEQ_GdycVDnxwCvtbo',
    appId: '1:692238134417:web:56bd135960c27ba73d2330',
    messagingSenderId: '692238134417',
    projectId: 'karaneeyaani',
    authDomain: 'karaneeyaani.firebaseapp.com',
    storageBucket: 'karaneeyaani.firebasestorage.app',
    measurementId: 'G-QQ8GE7SVQ8',
  );
}
